version: '3.4'

networks:
  socomap:
    driver: bridge

x-defaults:
  &defaults
  hostname: '{{.Service.Name}}'
  restart: on-failure
  networks:
    - socomap
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"

services:
  socomap:
    image: infotechgmbh/socomap:latest
    << : *defaults
    ports:
      - 81:8080
    environment:
      DBHOST: db
      DBNAME: socomap
      DBUSER: socomap
      DBPASS: test

  db:
    image: postgres:11.1
    << : *defaults
    environment:
      POSTGRES_USER: socomap
      POSTGRES_PASSWORD: test
      POSTGRES_DB: socomap
      PGDATA: /dbdata
    ports:
      - 5432:5432
    volumes:
      - socomap:/dbdata

  adminer:
    image: adminer:latest
    << : *defaults
    ports:
      - 82:8080

volumes: 
  socomap: